chore(deps): update to latest version of k8s-objects
kubewarden/namespace-label-propagator-policy pull request #22
Opened 2024-01-29 14:40 UTC by flavio

Use latest version of k8s-objects. This includes the fix of https://github.com/kubewarden/kubewarden-controller/issues/570 which is required by this policy when mutating resources.

2024-01-29 16:17 UTC, viccuad approved these changes

2024-01-29 16:19 UTC, viccuad requested changes
Wait, this policy is not for public consumption, correct?
If so, we shouldn't add the artifacthub-pkg.yml file, but set in the test workflow input `artifacthub: false`, see https://github.com/kubewarden/github-actions/blob/main/.github/workflows/reusable-test-policy-go.yml#L6-L10.

2024-01-30 09:19 UTC, flavio commented
@viccuad good point. I've updated the PR

2024-01-30 10:22 UTC, viccuad approved these changes

2024-01-30 10:24 UTC, fabriziosestito approved these changes

2024-01-30 12:06 UTC, merged